In [163]:
import requests
import json
import pandas as pd

In [18]:
res = requests.get("https://www.accesscanberra.act.gov.au/cc/mappingService/getDataPotholes")
potholes = res.json()

In [19]:
res = requests.get("https://www.accesscanberra.act.gov.au/cc/mappingService/getDataTrollies")
trollies = res.json()

In [20]:
res = requests.get("https://www.accesscanberra.act.gov.au/cc/mappingService/getDataStreetlights")
streetlights = res.json()

In [21]:
res = requests.get("https://www.accesscanberra.act.gov.au/cc/mappingService/getDataTrees")
trees = res.json()

In [29]:
potholes_df = pd.read_json(potholes)
trollies_df = pd.read_json(trollies)
streetlights_df = pd.read_json(streetlights)
trees_df = pd.read_json(trees)
df = potholes_df.append(trollies_df)
df = df.append(streetlights_df)
df = df.append(trees_df)

In [25]:
potholes_df.head()

,Address,Index,Latitude,Longitude,Status,SuburbName,Type
0,"52 Henty St, Braddon ACT 2612, Australia",0,-35.269284,149.133437,In Progress,Braddon,Shopping Trolley
1,"Moyes Cres, Holt ACT 2615, Australia",1,-35.223519,149.024365,In Progress,Holt,Shopping Trolley
2,"21 Bowes St, Phillip ACT 2606, Australia",2,-35.343350,149.086160,In Progress,Phillip,Shopping Trolley
3,"6 Bowes St, Phillip ACT 2606, Australia",3,-35.342790,149.085800,In Progress,Phillip,Shopping Trolley
4,"16 Lutana St, Lyons ACT 2606, Australia",4,-35.346953,149.076029,In Progress,Lyons,Shopping Trolley

In [26]:
trollies_df.head()

,Address,Index,Latitude,Longitude,Status,SuburbName,Type
0,"52 Henty St, Braddon ACT 2612, Australia",0,-35.269284,149.133437,In Progress,Braddon,Shopping Trolley
1,"Moyes Cres, Holt ACT 2615, Australia",1,-35.223519,149.024365,In Progress,Holt,Shopping Trolley
2,"21 Bowes St, Phillip ACT 2606, Australia",2,-35.343350,149.086160,In Progress,Phillip,Shopping Trolley
3,"6 Bowes St, Phillip ACT 2606, Australia",3,-35.342790,149.085800,In Progress,Phillip,Shopping Trolley
4,"16 Lutana St, Lyons ACT 2606, Australia",4,-35.346953,149.076029,In Progress,Lyons,Shopping Trolley

In [27]:
streetlights_df.head()

,Address,Index,Latitude,Longitude,Status,SuburbName,Type
0,"19A Diamantina Cres, Kaleen ACT 2617, Australia",0,-35.229230,149.100223,In Progress,Kaleen,Street Lights
1,"Unit 7/16 Neil Harris Cres, Forde ACT 2914, Au...",1,-35.175291,149.140957,In Progress,Forde,Street Lights
2,"2-4 Marsden St, Dickson ACT 2602, Australia",2,-35.254156,149.144941,In Progress,Dickson,Street Lights
3,"15 Dunphy St, Wright ACT 2611, Australia",3,-35.324214,149.039683,In Progress,Wright,Street Lights
4,"7-9 Shara Pl, Ngunnawal ACT 2913, Australia",4,-35.178021,149.113379,In Progress,Ngunnawal,Street Lights

In [28]:
trees_df.head()

,Address,Index,Latitude,Longitude,Status,SuburbName,Type
0,"3 Thurgood Ct, Gordon ACT 2906, Australia",0,-35.469878,149.087865,Updated,Gordon,Trees & Shrubs
1,"4 Sewell Pl, MacGregor ACT 2615, Australia",1,-35.217520,149.014474,Updated,Macgregor,Trees & Shrubs
2,"121 Easty St, Phillip ACT 2606, Australia",2,-35.345500,149.090990,Updated,Phillip,Trees & Shrubs
3,"54 Fitzhardinge Cres, Evatt ACT 2617, Australia",3,-35.216460,149.068579,In Progress,Evatt,Trees & Shrubs
4,"27 Olympus Way, Lyons ACT 2606, Australia",4,-35.340240,149.073304,Updated,Lyons,Trees & Shrubs

In [33]:
df = df[['Type','Address','SuburbName','Latitude','Longitude','Status']].reindex()

In [34]:
df

,Type,Address,SuburbName,Latitude,Longitude,Status
0,Pot Holes,"Gungahlin Dr & Belconnen Way, Bruce ACT 2617, ...",Bruce,-35.257073,149.090130,In Progress
1,Pot Holes,"5 Geelong St, Fyshwick ACT 2609, Australia",Fyshwick,-35.332301,149.167515,In Progress
2,Pot Holes,"29 Thynne St, Bruce ACT 2617, Australia",Bruce,-35.243175,149.093639,In Progress
3,Pot Holes,"Theatre Ln, Canberra ACT 2601, Australia",City,-35.281049,149.130441,In Progress
4,Pot Holes,"6-12 Banjine St, O'Connor ACT 2602, Australia",Not Identified,-35.253772,149.123478,In Progress
5,Pot Holes,"4 Bluebell St, O'Connor ACT 2602, Australia",O'Connor,-35.263917,149.122021,In Progress
6,Pot Holes,"Horse Park Dr, Australian Capital Territory 29...",Not Identified,-35.201919,149.167535,In Progress
7,Pot Holes,"7 Arakoon Cres, Isabella Plains ACT 2905, Aust...",Not Identified,-35.428372,149.091740,In Progress
8,Pot Holes,None,Not Identified,-35.274255,149.128510,In Progress
9,Pot Holes,"Horse Park Dr, Australian Capital Territory 29...",Forde,-35.208471,149.171227,In Progress
10,Pot Holes,"Horse Park Dr, Australian Capital Territory 29...",Harrison,-35.201503,149.166967,In Progress
11,Pot Holes,"Well Station Dr, Harrison ACT 2914, Australia",Harrison,-35.201807,149.164302,In Progress
12,Pot Holes,"corner of buxton and MacGregor St, Deakin ACT ...",Not Identified,-35.316235,149.106113,In Progress
13,Pot Holes,"Majura Parkway, Australian Capital Territory 2...",Not Identified,-35.219212,149.195340,In Progress
14,Pot Holes,"120 Hodgson Cres, Pearce ACT 2607, Australia",Pearce,-35.367554,149.084453,In Progress
15,Pot Holes,"Ginninderra Dr, Evatt ACT 2617, Australia",Evatt,-35.219981,149.055571,In Progress
16,Pot Holes,"121 William Hovell Dr, Molonglo Valley ACT 261...",Molonglo Valley,-35.276739,149.077488,In Progress
17,Pot Holes,"Belconnen Way, Bruce ACT 2617, Australia",Bruce,-35.252059,149.080470,In Progress
18,Pot Holes,"19B McCaughey St, Turner ACT 2612, Australia",Turner,-35.270998,149.123084,In Progress
19,Pot Holes,"Ginninderra Dr, Evatt ACT 2617, Australia",Evatt,-35.220132,149.055461,In Progress
20,Pot Holes,"Caswell Drive & Belconnen Way, Australian Capi...",Not Identified,-35.260599,149.087492,In Progress
21,Pot Holes,"1147 National Highway 25, Australian Capital T...",Yarralumla,-35.190536,149.081225,In Progress
22,Pot Holes,"Gungahlin Dr, Gungahlin ACT 2912, Australia",Gungahlin,-35.202385,149.132474,In Progress
23,Pot Holes,"Gungahlin Drive & Belconnen Way, Bruce ACT 261...",Bruce,-35.255687,149.091999,In Progress
24,Pot Holes,"121 William Hovell Dr, Molonglo Valley ACT 261...",Molonglo Valley,-35.276725,149.077117,In Progress
25,Pot Holes,"163 Badimara St, Fisher ACT 2611, Australia",Fisher,-35.358423,149.058550,In Progress
26,Pot Holes,"Caswell Drive & Belconnen Way, Australian Capi...",Not Identified,-35.261306,149.087246,In Progress
27,Pot Holes,"Belconnen Way, Belconnen ACT 2617, Australia",Holt,-35.244785,149.060159,In Progress
28,Pot Holes,"29 Badham St, Dickson ACT 2602, Australia",Dickson,-35.250206,149.137826,In Progress
29,Pot Holes,"Gungahlin Dr, Mitchell ACT 2911, Australia",Mitchell,-35.206679,149.132733,Updated
...,...,...,...,...,...,...
312,Trees & Shrubs,"1 Willoughby Cres, Gilmore ACT 2905, Australia",Gilmore,-35.412289,149.134517,In Progress
313,Trees & Shrubs,"10 Reader Ct, Banks ACT 2906, Australia",Banks,-35.471631,149.092443,In Progress
314,Trees & Shrubs,"29 Bettie Maloney, Banks ACT 2906, Australia",Banks,-35.471197,149.096155,In Progress
315,Trees & Shrubs,"Garran Shopping Centre, Garran Pl, Garran ACT ...",Garran,-35.342526,149.108279,In Progress
316,Trees & Shrubs,"10 Traynor Ct, Melba ACT 2615, Australia",Melba,-35.216907,149.050541,In Progress
317,Trees & Shrubs,"Kinloch Circuit, Bruce ACT 2617, Australia",Bruce,-35.239833,149.101560,In Progress
318,Trees & Shrubs,"Belconnen Way, Bruce ACT 2617, Australia",Bruce,-35.250643,149.077563,Unresolved
319,Trees & Shrubs,"Unit 2/45 Totterdell St, Belconnen ACT 2617, A...",Belconnen,-35.233460,149.061022,In Progress
320,Trees & Shrubs,"52 Hanrahan Cres, Dunlop ACT 2615, Australia",Dunlop,-35.186522,149.030988,Unresolved
321,Trees & Shrubs,"12-14 Wagga St, Farrer ACT 2607, Australia",Farrer,-35.381160,149.109736,Unresolved
322,Trees & Shrubs,"3 Sloane Pl, Florey ACT 2615, Australia",Florey,-35.221117,149.056941,In Progress
323,Trees & Shrubs,"9 McNicoll St, Hughes ACT 2605, Australia",Hughes,-35.334356,149.095521,In Progress
324,Trees & Shrubs,"40 Boolimba Cres, Narrabundah ACT 2604, Australia",Narrabundah,-35.333265,149.153454,Unresolved
325,Trees & Shrubs,"47 Magenta Square, Amaroo ACT 2914, Australia",Amaroo,-35.171453,149.121388,Unresolved
326,Trees & Shrubs,"Wybalena Grove, Cook ACT 2614, Australia",Cook,-35.262980,149.071764,Updated
327,Trees & Shrubs,"Hibberson St, Gungahlin ACT 2912, Australia",Gungahlin,-35.185046,149.131915,Unresolved
328,Trees & Shrubs,"8 Bramston St, Fadden ACT 2904, Australia",Fadden,-35.405142,149.119088,Unresolved
329,Trees & Shrubs,"16 Carpentaria St, Harrison ACT 2914, Australia",Harrison,-35.196199,149.161420,Unresolved
330,Trees & Shrubs,"Uniting Church, 17 Comrie St, Wanniassa ACT 29...",Wanniassa,-35.402400,149.099421,In Progress
331,Trees & Shrubs,"45 Bucknel Circuit, Isabella Plains ACT 2905, ...",Isabella Plains,-35.430659,149.103144,In Progress
332,Trees & Shrubs,"2/51 Mort St, Braddon ACT 2612, Australia",Braddon,-35.271870,149.131118,In Progress
333,Trees & Shrubs,"53 Nemarang Cres, Waramanga ACT 2611, Australia",Waramanga,-35.356879,149.061513,In Progress
334,Trees & Shrubs,"2/51 Mort St, Braddon ACT 2612, Australia",Braddon,-35.271870,149.131118,In Progress
335,Trees & Shrubs,"85 Nettlefold St, Belconnen ACT 2617, Australia",Belconnen,-35.243271,149.062907,Unresolved
336,Trees & Shrubs,"Sutton Rd, Australia",Majura,-35.248090,149.261447,In Progress
337,Trees & Shrubs,"Hall Street, Lyneham ACT 2602, Australia",Lyneham,-35.252003,149.125341,In Progress
338,Trees & Shrubs,"14 Revell Cl, Gordon ACT 2906, Australia",Gordon,-35.471750,149.089572,In Progress
339,Trees & Shrubs,"19 Olary St, Amaroo ACT 2914, Australia",Amaroo,-35.168988,149.134472,In Progress
340,Trees & Shrubs,"9 Swanton St, Chisholm ACT 2905, Australia",Chisholm,-35.422388,149.113033,Unresolved
341,Trees & Shrubs,"11 Castleton Cres, Gowrie ACT 2904, Australia",Gowrie,-35.414294,149.109423,Unresolved

In [39]:
df['Location'] = df['Latitude'].map(str) + ',' + df['Longitude'].map(str)
df.head()

,Type,Address,SuburbName,Latitude,Longitude,Status,Location
0,Pot Holes,"Gungahlin Dr & Belconnen Way, Bruce ACT 2617, ...",Bruce,-35.257073,149.090130,In Progress,"-35.25707348290413,149.09012993942508"
1,Pot Holes,"5 Geelong St, Fyshwick ACT 2609, Australia",Fyshwick,-35.332301,149.167515,In Progress,"-35.3323013,149.16751520000003"
2,Pot Holes,"29 Thynne St, Bruce ACT 2617, Australia",Bruce,-35.243175,149.093639,In Progress,"-35.24317484366189,149.09363868366427"
3,Pot Holes,"Theatre Ln, Canberra ACT 2601, Australia",City,-35.281049,149.130441,In Progress,"-35.28104925190457,149.1304408525906"
4,Pot Holes,"6-12 Banjine St, O'Connor ACT 2602, Australia",Not Identified,-35.253772,149.123478,In Progress,"-35.2537725,149.12347840000007"

In [40]:
df.to_csv("FixMyStreet_Extract.csv", index=False)

In [ ]:
res = request.get("https://www.yellowmap.de/Presentation/AldiSued/en-AU/ResultList?callback=jQuery20305086638138514932_1536450663170&LocX=133.77513&LocY=-25.27439&HiddenBranchCode=&BranchCode=&Lux=148.66973876953125&Luy=-35.06822115985924&Rlx=149.490966796875&Rly=-35.76211479572099&ZoomLevel=10&Mode=None&Filters.OPEN=false&Filters.ASxFIWI%26ASxFIBE=false&Filters.ASxFIWC=false&Filters.ASxFIPA=false&_=1536450663180")
res.json()

- Skate parks
- Basketball courts
- Fitness Sites
- Tennis?
- Sport grounds
- Playgrounds


- Dog parks


- Drinking fountents


- Toilets

In [41]:
!pwd

/Users/nlindorff/Documents/GovHack2018/Notebooks

In [63]:
sp_df = pd.read_csv('../ACT Location Data/Skate_Parks.csv')
sp_df['TYPE'] = 'Skate Park'
sp_df['CATEGORY'] = 'Skate Park'
sp_df.head()

,ID,DIVISION,LOCATION,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1,TYPE,CATEGORY
0,Skpk1,Belconnen,Emu Bank Pedestrian Parkland,NaN,NaN,-35.239332,149.072554,"(-35.239332, 149.072554)",Skate Park,Skate Park
1,Skpk16,Campbell,White Crescent Neighbourhood Park,NaN,NaN,-35.288843,149.155446,"(-35.288843, 149.155446)",Skate Park,Skate Park
2,Skpk11,Charnwood,Barnes Place Neighbourhood Park,NaN,NaN,-35.196038,149.038845,"(-35.196038, 149.038845)",Skate Park,Skate Park
3,Skpk6,City,Ballumbir Street,NaN,NaN,-35.278130,149.134620,"(-35.27813, 149.13462)",Skate Park,Skate Park
4,Skpk9,Fadden,Fadden Pines District Park,NaN,NaN,-35.409974,149.120424,"(-35.409974, 149.120424)",Skate Park,Skate Park

In [64]:
bc_df = pd.read_csv('../ACT Location Data/Basketball_Courts.csv')
bc_df['CATEGORY'] = 'Basketball Court'
bc_df.head()

,ID,TYPE,DIVISION,LOCATION,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1,CATEGORY
0,Bskt2,Single Court,Ainslie,Corroboree Park,NaN,NaN,-35.268338,149.141855,"(-35.268338, 149.141855)",Basketball Court
1,Bskt29,Double Court,Belconnen,John Knight Memorial Park,NaN,NaN,-35.237826,149.074645,"(-35.237826, 149.074645)",Basketball Court
2,Bskt17,Half Court,Bonython,Burgoyne Street Neighbourhood Park,NaN,NaN,-35.426712,149.071640,"(-35.426712, 149.07164)",Basketball Court
3,Bskt24,Half Court,Chifley,Shann Place Neighbourhood Park,NaN,NaN,-35.352159,149.077012,"(-35.352159, 149.077012)",Basketball Court
4,Bskt27,Half Court,City,City Youth Centre Basket Ball Court,NaN,NaN,-35.277923,149.134538,"(-35.277923, 149.134538)",Basketball Court

In [53]:
fs_df = pd.read_csv('../ACT Location Data/Fitness_Sites.csv')
fs_df.sort_values('LOCATION')
# fs_df

,ID,TYPE,DIVISION,LOCATION,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1
0,112,Sit Up Bench,Ainslie,Ainslie Football Park,NaN,NaN,-35.263555,149.138529,"(-35.263555, 149.138529)"
126,106,Horizontal Ladder,Ainslie,Ainslie Football Park,NaN,NaN,-35.262629,149.138784,"(-35.262629, 149.138784)"
124,109,Balance Beam,Ainslie,Ainslie Football Park,NaN,NaN,-35.263009,149.138715,"(-35.263009, 149.138715)"
111,110,Vault,Ainslie,Ainslie Football Park,NaN,NaN,-35.263033,149.138728,"(-35.263033, 149.138728)"
73,111,Step Ups,Ainslie,Ainslie Football Park,NaN,NaN,-35.263536,149.138549,"(-35.263536, 149.138549)"
67,108,Chinup Bar,Ainslie,Ainslie Football Park,NaN,NaN,-35.262985,149.138734,"(-35.262985, 149.138734)"
80,107,Parallel Bars,Ainslie,Ainslie Football Park,NaN,NaN,-35.262681,149.138779,"(-35.262681, 149.138779)"
107,167,Sit Up Bench,Yarralumla,Alexandrina Drive - Native Grassland Site,NaN,NaN,-35.298517,149.111757,"(-35.298517, 149.111757)"
29,168,Parallel Bars,Yarralumla,Alexandrina Drive - Native Grassland Site,NaN,NaN,-35.298054,149.111102,"(-35.298054, 149.111102)"
87,165,Sit Up Bench,Yarralumla,Alexandrina Drive - Pedestrian Parkland,NaN,NaN,-35.299756,149.112865,"(-35.299756, 149.112865)"
88,170,Chinup Bar,Yarralumla,Alexandrina Drive - Pedestrian Parkland,NaN,NaN,-35.296682,149.108409,"(-35.296682, 149.108409)"
100,166,Other,Yarralumla,Alexandrina Drive - Pedestrian Parkland,NaN,NaN,-35.299631,149.111371,"(-35.299631, 149.111371)"
191,162,Push Ups,Yarralumla,Alexandrina Drive - Pedestrian Parkland,NaN,NaN,-35.299931,149.115972,"(-35.299931, 149.115972)"
15,164,Step Ups,Yarralumla,Alexandrina Drive - Pedestrian Parkland,NaN,NaN,-35.299535,149.112963,"(-35.299535, 149.112963)"
62,161,Parallel Bars,Yarralumla,Alexandrina Drive - Pedestrian Parkland,NaN,NaN,-35.300346,149.116812,"(-35.300346, 149.116812)"
160,247,Hurdles,Yarralumla,Alexandrina Drive - Road Verge,NaN,NaN,-35.298986,149.114236,"(-35.298986, 149.114236)"
147,289,Other,Yarralumla,Alexandrina Drive Pedestrian Parkland,NaN,NaN,-35.297366,149.108902,"(-35.297366, 149.108902)"
187,246,Chinup Bar,Forde,Amy Ackman Street Pedestrian Parkland,NaN,NaN,-35.170142,149.142171,"(-35.170142, 149.142171)"
169,287,Stretching Equipment,Ainslie,Angas Street Road Verge,NaN,NaN,-35.263595,149.138500,"(-35.263595, 149.1385)"
135,260,Step Ups,Rivett,Bangalay Crescent Neighbourhood Park,NaN,NaN,-35.347911,149.037840,"(-35.347911, 149.03784)"
148,261,Sit Up Bench,Rivett,Bangalay Crescent Neighbourhood Park,NaN,NaN,-35.347981,149.037607,"(-35.347981, 149.037607)"
155,262,Stretching Equipment,Rivett,Bangalay Crescent Neighbourhood Park,NaN,NaN,-35.347917,149.037421,"(-35.347917, 149.037421)"
167,259,Parallel Bars,Holt,Beaurepaire Crescent Neighbourhood Park,NaN,NaN,-35.222043,149.013459,"(-35.222043, 149.013459)"
139,257,Chinup Bar,Holt,Beaurepaire Crescent Neighbourhood Park,NaN,NaN,-35.222584,149.013194,"(-35.222584, 149.013194)"
189,258,Push Ups,Holt,Beaurepaire Crescent Neighbourhood Park,NaN,NaN,-35.222343,149.013437,"(-35.222343, 149.013437)"
110,187,Ping Pong Table,Bonner,Bilin Bilins Treet Neighbourhood Park,NaN,NaN,-35.152422,149.147076,"(-35.152422, 149.147076)"
171,248,Chinup Bar,Kambah,Boddington Crescent Neighbourhood Park,NaN,NaN,-35.383480,149.052062,"(-35.38348, 149.052062)"
201,401,Body Pulls & Push Ups,Moncrieff,Bon Scott Crescent Crip Park,NaN,NaN,-35.155474,149.120825,"(-35.155474, 149.120825)"
200,421,Aerobic Walker,Moncrieff,Bon Scott Crescent Crip Park,NaN,NaN,-35.155466,149.120808,"(-35.155466, 149.120808)"
199,381,Leg Press,Moncrieff,Bon Scott Crescent Crip Park,NaN,NaN,-35.155480,149.120841,"(-35.15548, 149.120841)"
...,...,...,...,...,...,...,...,...,...
50,41,Stretching Equipment,Wright,Swallowtail Road Road Verge,NaN,NaN,-35.325110,149.030703,"(-35.32511, 149.030703)"
144,254,Chinup Bar,Cook,Templeton Crescent Neighbourhood Park,NaN,NaN,-35.258394,149.062190,"(-35.258394, 149.06219)"
178,251,Jump To Touch,Cook,Templeton Crescent Neighbourhood Park,NaN,NaN,-35.258412,149.062102,"(-35.258412, 149.062102)"
168,253,Sit Up Bench,Cook,Templeton Crescent Neighbourhood Park,NaN,NaN,-35.258367,149.062138,"(-35.258367, 149.062138)"
181,252,Parallel Bars,Cook,Templeton Crescent Neighbourhood Park,NaN,NaN,-35.258439,149.062162,"(-35.258439, 149.062162)"
82,224,Step Ups,Coombs,Terry Connolly Street Pedestrian Parkland,NaN,NaN,-35.321073,149.045264,"(-35.321073, 149.045264)"
60,225,Step Ups,Coombs,Terry Connolly Street Pedestrian Parkland,NaN,NaN,-35.321110,149.045285,"(-35.32111, 149.045285)"
19,49,Roman Rings,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411578,149.067443,"(-35.411578, 149.067443)"
44,51,Aerobic Walker,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411546,149.067474,"(-35.411546, 149.067474)"
74,183,Chinup Bar,Greenway,Tuggeranong Town Park,NaN,NaN,-35.412334,149.068039,"(-35.412334, 149.068039)"
1,50,Chinup Bar,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411585,149.067439,"(-35.411585, 149.067439)"
23,47,Chinup Bar,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411574,149.067434,"(-35.411574, 149.067434)"
25,45,Horizontal Bar,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411555,149.067435,"(-35.411555, 149.067435)"
17,46,Pull Ups,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411570,149.067424,"(-35.41157, 149.067424)"
10,53,Parallel Bars,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411581,149.067492,"(-35.411581, 149.067492)"
33,48,Chinup Bar,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411582,149.067429,"(-35.411582, 149.067429)"
39,55,Leg Press,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411604,149.067451,"(-35.411604, 149.067451)"
64,54,Sit Up Bench,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411594,149.067483,"(-35.411594, 149.067483)"
5,52,Push Ups,Greenway,Tuggeranong Town Park,NaN,NaN,-35.411576,149.067480,"(-35.411576, 149.06748)"
35,138,Stretching Equipment,Kaleen,Woronora Street Pedestrian Parkland,NaN,NaN,-35.221283,149.111595,"(-35.221283, 149.111595)"
72,137,Chinup Bar,Kaleen,Woronora Street Pedestrian Parkland,NaN,NaN,-35.221110,149.113211,"(-35.22111, 149.113211)"
24,134,Parallel Bars,Kaleen,Woronora Street Pedestrian Parkland,NaN,NaN,-35.221651,149.112538,"(-35.221651, 149.112538)"
81,213,Bench Dip,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178073,149.130640,"(-35.178073, 149.13064)"
120,207,Multi Station,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178025,149.130655,"(-35.178025, 149.130655)"
83,209,Step Ups,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178047,149.130660,"(-35.178047, 149.13066)"
65,211,Leg Raises & Pull Ups,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178049,149.130635,"(-35.178049, 149.130635)"
11,210,Pull Ups,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178029,149.130632,"(-35.178029, 149.130632)"
70,208,Step Ups,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178035,149.130659,"(-35.178035, 149.130659)"
118,212,Multi Station,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178070,149.130662,"(-35.17807, 149.130662)"
190,231,Sit Up Bench,Forde,Zakharov Avenue Pedestrian Parkland,NaN,NaN,-35.172773,149.143759,"(-35.172773, 149.143759)"

In [54]:
pg_df = pd.read_csv('../ACT Location Data/Town_And_District_Playgrounds.csv')
pg_df.head()

,ASSET_ID,EQUIPMENT,LOCATION,DIVISION_NAME,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1
0,Plgr178,This playground has 4 play areas with a total ...,Finn Street Neighbouhood Park,O'connor,NaN,NaN,-35.260888,149.118359,"(-35.260888, 149.118359)"
1,Plgr228,This playground has 3 play areas with a total ...,Coyne Street District Park,Fadden,NaN,NaN,-35.411025,149.120551,"(-35.411025, 149.120551)"
2,Plgr219,This playground has 2 play areas with a total ...,Cremone Place Neighbourhood Park,Conder,NaN,NaN,-35.464393,149.102991,"(-35.464393, 149.102991)"
3,Plgr271,This playground has 1 play area with a total o...,Sangster Place Shopping Centre,Wanniassa,NaN,NaN,-35.390616,149.085639,"(-35.390616, 149.085639)"
4,Plgr278,This playground has 7 play areas with a total ...,Mcgilvray Close District Park,Gordon,NaN,NaN,-35.456079,149.083775,"(-35.456079, 149.083775)"

In [55]:
sp_df

,ID,DIVISION,LOCATION,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1
0,Skpk1,Belconnen,Emu Bank Pedestrian Parkland,NaN,NaN,-35.239332,149.072554,"(-35.239332, 149.072554)"
1,Skpk16,Campbell,White Crescent Neighbourhood Park,NaN,NaN,-35.288843,149.155446,"(-35.288843, 149.155446)"
2,Skpk11,Charnwood,Barnes Place Neighbourhood Park,NaN,NaN,-35.196038,149.038845,"(-35.196038, 149.038845)"
3,Skpk6,City,Ballumbir Street,NaN,NaN,-35.278130,149.134620,"(-35.27813, 149.13462)"
4,Skpk9,Fadden,Fadden Pines District Park,NaN,NaN,-35.409974,149.120424,"(-35.409974, 149.120424)"
5,Skpk19,Flynn,George Simpson Park Surround,NaN,NaN,-35.207598,149.044027,"(-35.207598, 149.044027)"
6,Skpk3,Greenway,Tuggeranong Town Park,NaN,NaN,-35.410104,149.064239,"(-35.410104, 149.064239)"
7,Skpk12,Gungahlin,Yerrabi District Park,NaN,NaN,-35.178893,149.131016,"(-35.178893, 149.131016)"
8,Skpk2,Gungahlin,Yerrabi District Park,NaN,NaN,-35.180126,149.129395,"(-35.180126, 149.129395)"
9,Skpk10,Holt,Moyes Cresent Pedestrian Parkland,NaN,NaN,-35.221120,149.020255,"(-35.22112, 149.020255)"
10,Skpk14,Kambah,Kambah District Park,NaN,NaN,-35.392839,149.063552,"(-35.392839, 149.063552)"
11,Skpk17,Macarthur,Hawkesworth Place Neighbourhood Park,NaN,NaN,-35.408198,149.129023,"(-35.408198, 149.129023)"
12,Skpk7,Phillip,Eddison Town Park,NaN,NaN,-35.339971,149.091375,"(-35.339971, 149.091375)"
13,Skpk18,Richardson,Clift Crescent Pedestrian Parkland,NaN,NaN,-35.427073,149.115193,"(-35.427073, 149.115193)"
14,Skpk15,Rivett,Sollya Place Pedestrian Parkland,NaN,NaN,-35.349358,149.032661,"(-35.349358, 149.032661)"
15,Skpk13,Stirling,Sherratt Place Pedestrian Parkland,NaN,NaN,-35.349766,149.045266,"(-35.349766, 149.045266)"
16,Skpk8,Wanniassa,Creman Close Pedestrian Parkland,NaN,NaN,-35.402487,149.097508,"(-35.402487, 149.097508)"
17,Skpk4,Weston,Dillon Close - Pedestrian Parkland,NaN,NaN,-35.337431,149.053905,"(-35.337431, 149.053905)"
18,Skpk21,Franklin,Kilmeny Close Community Park (Crip),NaN,NaN,-35.196972,149.143726,"(-35.196972, 149.143726)"
19,Skpk20,Conder,Sidney Nolan Street,NaN,NaN,-35.458384,149.094805,"(-35.458384, 149.094805)"
20,Skpk5,Barton,Telopea Park,NaN,NaN,-35.316038,149.136052,"(-35.316038, 149.136052)"

In [154]:
sport_df = sp_df.append(bc_df)
# sport_df = sport_df.append(pg_df)
sport_df['LOCATION_NAME'] = sport_df['LOCATION']
sport_df = sport_df[['ID','LATITUDE','LONGITUDE','CATEGORY','TYPE','DIVISION','LOCATION_NAME','Location_1']]
sport_df.head()

,ID,LATITUDE,LONGITUDE,CATEGORY,TYPE,DIVISION,LOCATION_NAME,Location_1
0,Skpk1,-35.239332,149.072554,Skate Park,Skate Park,Belconnen,Emu Bank Pedestrian Parkland,"(-35.239332, 149.072554)"
1,Skpk16,-35.288843,149.155446,Skate Park,Skate Park,Campbell,White Crescent Neighbourhood Park,"(-35.288843, 149.155446)"
2,Skpk11,-35.196038,149.038845,Skate Park,Skate Park,Charnwood,Barnes Place Neighbourhood Park,"(-35.196038, 149.038845)"
3,Skpk6,-35.278130,149.134620,Skate Park,Skate Park,City,Ballumbir Street,"(-35.27813, 149.13462)"
4,Skpk9,-35.409974,149.120424,Skate Park,Skate Park,Fadden,Fadden Pines District Park,"(-35.409974, 149.120424)"

In [155]:
sport_df.to_csv('ACT_Sport_Grounds_Locations.csv', index=False)

# Amenities
- Drinking Fountains
- Toilets
- Furnature

In [156]:
drink_df = pd.read_csv('../ACT Location Data/Drinking_Fountains.csv')
drink_df.rename(columns = { 'LOCATION':'LOCATION_DESCRIPTION', 'category':'CATEGORY' }, inplace = True)
drink_df['CATEGORY'] = 'Drinking Fountain'
drink_df['TYPE'] = 'Drinking Fountain'
drink_df.head()

,ID,DIVISION,LOCATION_DESCRIPTION,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1,CATEGORY,TYPE
0,Drfn240,Acton,Black Mountain Peninsula District Park,NaN,NaN,-35.286323,149.101427,"-35.286323,149.101427",Drinking Fountain,Drinking Fountain
1,Drfn62,Acton,Black Mountain Peninsula District Park,NaN,NaN,-35.292273,149.101002,"-35.292273,149.101002",Drinking Fountain,Drinking Fountain
2,Drfn65,Acton,Black Mountain Peninsula District Park,NaN,NaN,-35.288357,149.100244,"-35.288357,149.100244",Drinking Fountain,Drinking Fountain
3,Drfn64,Acton,Black Mountain Peninsula District Park,NaN,NaN,-35.289413,149.099886,"-35.289413,149.099886",Drinking Fountain,Drinking Fountain
4,Drfn59,Acton,Black Mountain Peninsula District Park,NaN,NaN,-35.291521,149.100124,"-35.291521,149.100124",Drinking Fountain,Drinking Fountain

In [157]:
toilet_df = pd.read_csv('../ACT Location Data/Public_Toilets_in_the_ACT.csv')
toilet_df.rename(columns = {'ASSET_ID':'ID','DIVISION_NAME':'DIVISION', 'TOILET_TYPE_TEXT':'TYPE', 'Location':'Location_1'}, inplace = True)
toilet_df['TYPE'] = toilet_df.TYPE.str.title()
toilet_df['LOCATION_DESCRIPTION'] = toilet_df.LOCATION_DESCRIPTION.str.title()
toilet_df['DIVISION'] = toilet_df.DIVISION.str.title()
toilet_df['CATEGORY'] = 'Toilet'
toilet_df.head()

,ID,DIVISION,LOCATION_DESCRIPTION,TYPE,Location_1,LATITUDE,LONGITUDE,CATEGORY
0,TOLT127,Kowen (Rural Dist.),Molonglo Gorge,Manual Style Ablution Block,"(-35.322519, 149.246903)",-35.322519,149.246903,Toilet
1,TOLT82,Paddys River (Rural Dist.),Wetlands Carpark,Manual Style Ablution Block,"(-35.461472, 148.906841)",-35.461472,148.906841,Toilet
2,TOLT48,Griffith,Griffith Shopping Centre,Manual Style Ablution Block,"(-35.328262, 149.142196)",-35.328262,149.142196,Toilet
3,TOLT42,Fadden,Fadden Pines District Park,Manual Style Ablution Block,"(-35.411678, 149.120754)",-35.411678,149.120754,Toilet
4,TOLT26,Phillip,Phillip Town Centre,Manual Style Ablution Block,"(-35.352412, 149.087611)",-35.352412,149.087611,Toilet

In [158]:
furn_df = pd.read_csv('../ACT Location Data/Public_Furniture_in_the_ACT.csv')
furn_df.rename(columns = {'ASSET ID':'ID', 'FEATURE TYPE':'TYPE', 'LOCATION NAME':'LOCATION_DESCRIPTION', 'DIVISION NAME':'DIVISION', 'TOILET_TYPE_TEXT':'TYPE', 'Location':'Location_1'}, inplace = True)
furn_df['TYPE'] = furn_df.TYPE.str.title()
furn_df['LOCATION_DESCRIPTION'] = furn_df.LOCATION_DESCRIPTION.str.title()
furn_df['DIVISION'] = furn_df.DIVISION.str.title()
furn_df['CATEGORY'] = 'Furniture'
furn_df.head()

,ID,TYPE,DIVISION,LOCATION_DESCRIPTION,Location 1,LATITUDE,LONGITUDE,CATEGORY
0,TABL585,Table,Acton,Black Mountain Peninsula District Park,"(-35.292262, 149.100651)",-35.292262,149.100651,Furniture
1,TABL571,Table,Acton,Garryowen Drive,"(-35.287224, 149.101324)",-35.287224,149.101324,Furniture
2,TABL506,Table,Acton,Black Mountain Peninsula District Park,"(-35.292241, 149.101339)",-35.292241,149.101339,Furniture
3,TABL150,Table,Acton,Acton Park District Park,"(-35.289076, 149.126234)",-35.289076,149.126234,Furniture
4,TABL151,Table,Acton,Acton Park District Park,"(-35.288779, 149.126202)",-35.288779,149.126202,Furniture

In [160]:
amen_df = drink_df.append(toilet_df).append(furn_df)
amen_df = amen_df[['ID','CATEGORY','DIVISION','LATITUDE','LONGITUDE','LOCATION_DESCRIPTION','TYPE']]
amen_df.sample(20)

,ID,CATEGORY,DIVISION,LATITUDE,LONGITUDE,LOCATION_DESCRIPTION,TYPE
1825,SEAT304,Furniture,Greenway,-35.415731,149.070807,Tuggeranong Town Centre,Seat
1827,SEAT306,Furniture,Greenway,-35.415652,149.070496,Tuggeranong Town Centre,Seat
2042,SEAT2878,Furniture,Gungahlin,-35.176068,149.134242,Yerrabi District Park,Seat
901,SEAT1500,Furniture,City,-35.280678,149.135587,Glebe Park,Seat
109,TOLT6,Toilet,Charnwood,-35.205232,149.033642,Charnwood Shopping Centre,Manual Style Ablution Block
64,TOLT39,Toilet,Kambah,-35.380177,149.058396,Kambah Village,Manual Style Ablution Block
4498,SEAT5189,Furniture,Throsby,-35.187954,149.161893,Bettong Avenue Neighbourhood Park,Seat
4663,TABL2152,Furniture,Tennent (Rural Dist.),-35.582621,148.974343,Namadgi National Park,Table
181,Drfn210,Drinking Fountain,Canberra Central Rural Dist.,-35.274959,149.097714,Black Mountain,Drinking Fountain
79,Drfn227,Drinking Fountain,Phillip,-35.339885,149.091130,Eddison District Park,Drinking Fountain
548,SEAT4062,Furniture,Casey,-35.165644,149.099101,Renouf Street Pedestrian Parkland,Seat
4001,TABL1066,Furniture,Paddys River (Rural Dist.),-35.463352,148.910479,"Black Flats, Tidbinbilla Nature Reserve",Table
2935,SEAT3939,Furniture,Phillip,-35.339997,149.091056,Eddison District Park,Seat
246,TABL6,Furniture,Belconnen,-35.229667,149.075647,Ginninderra Peninsula District Park,Table
1263,SEAT1029,Furniture,Curtin,-35.333814,149.074846,Bavin Street - Pedestrian Parkland,Seat
695,SEAT1736,Furniture,City,-35.276091,149.128834,Civic Commercial Centre,Seat
287,SEAT4517,Furniture,Belconnen,-35.229026,149.073681,Diddams Close Pedestrian Parkland,Seat
301,SEAT2034,Furniture,Belconnen,-35.238009,149.068555,Margaret Timpson Park,Seat
2980,SEAT3214,Furniture,Phillip,-35.343487,149.088596,Phillip Town Centre,Seat
1463,SEAT506,Furniture,Fadden,-35.397905,149.117328,Hilton Close - Neighbourhood Park,Seat

In [161]:
amen_df.to_csv('ACT_Amenities.csv', index=False)

In [119]:
bbq_df = pd.read_csv('../ACT Location Data/Public_Barbeques_in_the_ACT.csv')
bbq_df.rename(columns = {'ASSET_ID':'ID', 'BBQ_TYPE':'TYPE', 'LOCATION':'DIVISION'}, inplace = True)
bbq_df['CATEGORY'] = 'BBQ'
bbq_df.head()

,ID,DIVISION,LOCATION_DESCRIPTION,TYPE,Location_1,LATITUDE,LONGITUDE,CATEGORY
0,BBQ134,Bonython,Derrington Crescent Pedestrian Parkland,Electric,"(-35.429604, 149.071265)",-35.429604,149.071265,BBQ
1,BBQ435,Greenway,Tuggeranong Town Park,Electric,"(-35.4099, 149.065091)",-35.409900,149.065091,BBQ
2,BBQ53,Gungahlin,Yerrabi District Park,Electric,"(-35.179366, 149.130643)",-35.179366,149.130643,BBQ
3,BBQ96,Fadden,Fadden Pines District Park,Electric,"(-35.410421, 149.120004)",-35.410421,149.120004,BBQ
4,BBQ73,Barton,Telopea Park,Electric,"(-35.314876, 149.137811)",-35.314876,149.137811,BBQ

In [146]:
pg_df = pd.read_csv('../ACT Location Data/Town_And_District_Playgrounds.csv')
pg_df.rename(columns = {'LOCATION':'LOCATION_DESCRIPTION', 'ASSET_ID':'ID', 'EQUIPMENT':'TYPE', 'DIVISION_NAME':'DIVISION'}, inplace = True)
pg_df['CATEGORY'] = 'Playground'
pg_df.head()

,ID,TYPE,LOCATION_DESCRIPTION,DIVISION,IMAGE_LINK,VIDEO_LINK,LATITUDE,LONGITUDE,Location_1,CATEGORY
0,Plgr178,This playground has 4 play areas with a total ...,Finn Street Neighbouhood Park,O'connor,NaN,NaN,-35.260888,149.118359,"(-35.260888, 149.118359)",Playground
1,Plgr228,This playground has 3 play areas with a total ...,Coyne Street District Park,Fadden,NaN,NaN,-35.411025,149.120551,"(-35.411025, 149.120551)",Playground
2,Plgr219,This playground has 2 play areas with a total ...,Cremone Place Neighbourhood Park,Conder,NaN,NaN,-35.464393,149.102991,"(-35.464393, 149.102991)",Playground
3,Plgr271,This playground has 1 play area with a total o...,Sangster Place Shopping Centre,Wanniassa,NaN,NaN,-35.390616,149.085639,"(-35.390616, 149.085639)",Playground
4,Plgr278,This playground has 7 play areas with a total ...,Mcgilvray Close District Park,Gordon,NaN,NaN,-35.456079,149.083775,"(-35.456079, 149.083775)",Playground

In [147]:
fam_df = bbq_df.append(pg_df)
fam_df = fam_df[['ID','CATEGORY','DIVISION','LATITUDE','LONGITUDE','LOCATION_DESCRIPTION','TYPE']]
fam_df.sample(10)

,ID,CATEGORY,DIVISION,LATITUDE,LONGITUDE,LOCATION_DESCRIPTION,TYPE
186,BBQ281,BBQ,Paddys River (Rural Dist.),-35.443210,148.926476,Greens Picnic Area,Wood
147,BBQ253,BBQ,Stromlo (Rural Dist.),-35.248608,148.952741,Uriarra East,Wood
56,Plgr580,Playground,Kambah,-35.385632,149.071252,Summerland Circuit (North) Neighbourhood Park,This playground has 5 play areas with a total ...
104,BBQ257,BBQ,Coree (Rural Dist.),-35.327194,148.938837,Cotter Bend,Electric
309,BBQ320,BBQ,Stromlo (Rural Dist.),-35.319801,148.954339,Cotter Reserve - Casuarina Sands,Electric
4,Plgr278,Playground,Gordon,-35.456079,149.083775,Mcgilvray Close District Park,This playground has 7 play areas with a total ...
9,BBQ427,BBQ,Yarralumla,-35.292516,149.093201,Weston Park,Electric
228,BBQ159,BBQ,Paddys River (Rural Dist.),-35.326293,148.938376,Thompsons Flat Picnic Area,Wood
18,Plgr207,Playground,Red Hill,-35.335927,149.126168,Golden Grove Neighbourhood Park,This playground has 1 play area with a total o...
280,BBQ449,BBQ,Paddys River (Rural Dist.),-35.442681,148.930129,Discovery Picnic Area,Electric

In [148]:
fam_df.to_csv('ACT_Family_Places.csv', index=False)

In [138]:
aldi_df = pd.read_excel('../ACT Location Data/Aldi_locations.xlsx')
# aldi_df.rename(columns = {'ASSET_ID':'ID','DIVISION_NAME':'DIVISION', 'TOILET_TYPE_TEXT':'TYPE', 'Location':'Location_1'}, inplace = True)
aldi_df['TYPE'] = 'Battery Disposal'
aldi_df['DIVISION'] = ''
aldi_df['LOCATION_DESCRIPTION'] = 'Aldi'
aldi_df['CATEGORY'] = 'Battery Disposal'
aldi_df.head()

,LATITUDE,LONGITUDE,TYPE,DIVISION,LOCATION_DESCRIPTION,CATEGORY
0,-35.270605,149.133387,Battery Disposal,,Aldi,Battery Disposal
1,-35.290706,149.189699,Battery Disposal,,Aldi,Battery Disposal
2,-35.341063,149.231018,Battery Disposal,,Aldi,Battery Disposal
3,-35.325550,149.055871,Battery Disposal,,Aldi,Battery Disposal
4,-35.399453,149.131500,Battery Disposal,,Aldi,Battery Disposal

In [139]:
recycling_df = aldi_df

In [140]:
recycling_df.to_csv('ACT_Recycling.csv', index=False)

In [164]:
res = requests.get('https://recyclingnearyou.com.au/queries/getBusinesses.cfm?lat=-35.13559&lon=149.31711&state=ACT&material_1=Batteries%2520-%2520Single%2520Use&material_2=Batteries%2520-%2520Rechargeable')

In [167]:
rec_json = res.json()

In [174]:
# rec_json['COLUMNS']
rec_df = pd.DataFrame(rec_json['DATA'])

In [178]:
rec_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 73 entries, 0 to 72
Data columns (total 28 columns):
ADDITIONALINFO     48 non-null object
ADDRESS            70 non-null object
BUSINESSNAME       73 non-null object
BUSINESS_ID        73 non-null int64
BUSINESS_UID       73 non-null object
DESCRIPTION        34 non-null object
DROPOFF            73 non-null bool
EMAIL              42 non-null object
FEES               73 non-null bool
GEO_LAT            72 non-null object
GEO_LON            72 non-null object
PHONE              51 non-null object
PICKUP             73 non-null bool
PICKUP_ACT         73 non-null bool
PICKUP_DETAILS     25 non-null object
PICKUP_NATIONAL    73 non-null bool
PICKUP_NSW         73 non-null bool
PICKUP_NT          73 non-null bool
PICKUP_QLD         73 non-null bool
PICKUP_SA          73 non-null bool
PICKUP_TAS         73 non-null bool
PICKUP_VIC         73 non-null bool
PICKUP_WA          73 non-null bool
POSTCODE           72 non-null object
PROVIDER_NAME      11 non-null object
STATE              73 non-null object
SUBURB             72 non-null object
WEBSITE            43 non-null object
dtypes: bool(12), int64(1), object(15)
memory usage: 10.1+ KB

In [183]:
# Sources 
# https://recyclingnearyou.com.au/batteries/ACT
# https://recyclingnearyou.com.au/queries/getBusinesses.cfm?lat=-35.13559&lon=149.31711&state=ACT&material_1=Batteries%2520-%2520Single%2520Use&material_2=Batteries%2520-%2520Rechargeable
rec_df = rec_df[rec_df['STATE']=='ACT']
rec_df = rec_df[rec_df['DROPOFF']==True]

rec_df[['ADDITIONALINFO','ADDRESS','BUSINESSNAME','BUSINESS_ID','BUSINESS_UID','DESCRIPTION','DROPOFF','EMAIL','FEES','GEO_LAT','GEO_LON','PHONE','POSTCODE','PROVIDER_NAME','STATE','SUBURB','WEBSITE']]

,ADDITIONALINFO,ADDRESS,BUSINESSNAME,BUSINESS_ID,BUSINESS_UID,DESCRIPTION,DROPOFF,EMAIL,FEES,GEO_LAT,GEO_LON,PHONE,POSTCODE,PROVIDER_NAME,STATE,SUBURB,WEBSITE
0,None,95 Grenville Court,Battery World,11000,02F24581-A0AF-9D1D-BB7CEDA1AB75ED60,None,True,None,True,-35.3510930,149.0890850,02 6282 9884,2606,None,ACT,Phillip,http://www.batteryworld.com.au/
1,None,95 Grenville Court,Battery World,11000,02F24581-A0AF-9D1D-BB7CEDA1AB75ED60,None,True,None,True,-35.3510930,149.0890850,02 6282 9884,2606,None,ACT,Phillip,http://www.batteryworld.com.au/
13,None,27 Mulley Street,ACT Deafness Resource Centre,13614,F71A049F-D26C-89DA-DA9CF4795F441CF5,We take full jars of hearing aid batteries for...,True,mark.parkinson@actdrc.org.au,False,-35.3314690,149.0495750,02 62874393,2611,None,ACT,Holder,http://www.actdrc.org.au
29,"Only AA, AAA, C, D and 9V batteries are accepted.",Hibberson St,Aldi,15412,7052C2E8-E377-5453-7A5A3A17D82A6EC9,None,True,None,False,-35.1853424,149.1335844,None,2912,None,ACT,Gungahlin,None
30,"Only AA, AAA, C, D and 9V batteries are accepted.",Hibberson St,Aldi,15412,7052C2E8-E377-5453-7A5A3A17D82A6EC9,None,True,None,False,-35.1853424,149.1335844,None,2912,None,ACT,Gungahlin,None
31,"Only AA, AAA, C, D and 9V batteries are accepted.",50-60 Hardwick Crescent,Aldi,15416,7052C3E2-FBCF-B0C3-BB88A2F047FE50C5,None,True,None,False,-35.2236367,149.0206452,None,2615,None,ACT,Kippax-holt,None
32,"Only AA, AAA, C, D and 9V batteries are accepted.",50-60 Hardwick Crescent,Aldi,15416,7052C3E2-FBCF-B0C3-BB88A2F047FE50C5,None,True,None,False,-35.2236367,149.0206452,None,2615,None,ACT,Kippax-holt,None
33,"Only AA, AAA, C, D and 9V batteries are accepted.",Canberra Centre,Aldi,15417,7052C420-D8E0-1E28-741DDA34B4B396A7,None,True,None,False,-35.2793620,149.1354980,None,2601,None,ACT,Canberra,None
34,"Only AA, AAA, C, D and 9V batteries are accepted.",Canberra Centre,Aldi,15417,7052C420-D8E0-1E28-741DDA34B4B396A7,None,True,None,False,-35.2793620,149.1354980,None,2601,None,ACT,Canberra,None
35,"Only AA, AAA, C, D and 9V batteries are accepted.",9 Sidney Nolan Street,Aldi,15418,7052C46F-0340-A861-205F5995F28116C2,None,True,None,False,-35.4570010,149.0936920,None,2906,None,ACT,Conder,None
36,"Only AA, AAA, C, D and 9V batteries are accepted.",9 Sidney Nolan Street,Aldi,15418,7052C46F-0340-A861-205F5995F28116C2,None,True,None,False,-35.4570010,149.0936920,None,2906,None,ACT,Conder,None
37,"Only AA, AAA, C, D and 9V batteries are accepted.",Bowman St,Aldi,15421,7052C51A-AAE2-897E-B38DA9EF4E5AFE56,None,True,None,False,-35.2534211,149.0696306,None,2614,None,ACT,Macquarie,None
38,"Only AA, AAA, C, D and 9V batteries are accepted.",Bowman St,Aldi,15421,7052C51A-AAE2-897E-B38DA9EF4E5AFE56,None,True,None,False,-35.2534211,149.0696306,None,2614,None,ACT,Macquarie,None
39,"Only AA, AAA, C, D and 9V batteries are accepted.",Brierly St,Aldi,15425,7052C5F5-A4F6-2BF1-30011367E6F10EE3,None,True,None,False,-35.3417400,149.0522793,None,2611,None,ACT,Weston,None
40,"Only AA, AAA, C, D and 9V batteries are accepted.",Brierly St,Aldi,15425,7052C5F5-A4F6-2BF1-30011367E6F10EE3,None,True,None,False,-35.3417400,149.0522793,None,2611,None,ACT,Weston,None
44,None,41 Alderson Place,Suez Environnement (SITA Australia),15768,19938AF1-C9EF-4656-15C9EC773C06CA6B,None,True,None,True,-35.4006210,149.1599340,13 13 35,2620,None,ACT,Hume,None
45,None,41 Alderson Place,Suez Environnement (SITA Australia),15768,19938AF1-C9EF-4656-15C9EC773C06CA6B,None,True,None,True,-35.4006210,149.1599340,13 13 35,2620,None,ACT,Hume,None
46,None,41 Alderson Place,Suez Environnement (SITA Australia),15768,19938AF1-C9EF-4656-15C9EC773C06CA6B,None,True,None,True,-35.4006210,149.1599340,13 13 35,2620,None,ACT,Hume,None
47,None,41 Alderson Place,Suez Environnement (SITA Australia),15768,19938AF1-C9EF-4656-15C9EC773C06CA6B,None,True,None,True,-35.4006210,149.1599340,13 13 35,2620,None,ACT,Hume,None
54,Photovoltaic Panels are collected.\r\n\r\nBatt...,78-80 Townsville St,MRI e-cycle solutions (Aust) Pty Ltd,17624,35C36432-E238-6845-BB3D83283D9AE171,We offer Australia wide recycling services for...,True,mri@mri.com.au,True,-35.3302340,149.1823900,1300 439 273,2609,Drop Zone ...,ACT,Fyshwick,http://www.mri.com.au
55,Photovoltaic Panels are collected.\r\n\r\nBatt...,78-80 Townsville St,MRI e-cycle solutions (Aust) Pty Ltd,17624,35C36432-E238-6845-BB3D83283D9AE171,We offer Australia wide recycling services for...,True,mri@mri.com.au,True,-35.3302340,149.1823900,1300 439 273,2609,Drop Zone ...,ACT,Fyshwick,http://www.mri.com.au
56,Photovoltaic Panels are collected.\r\n\r\nBatt...,78-80 Townsville St,MRI e-cycle solutions (Aust) Pty Ltd,17624,35C36432-E238-6845-BB3D83283D9AE171,We offer Australia wide recycling services for...,True,mri@mri.com.au,True,-35.3302340,149.1823900,1300 439 273,2609,Drop Zone ...,ACT,Fyshwick,http://www.mri.com.au
57,Photovoltaic Panels are collected.\r\n\r\nBatt...,78-80 Townsville St,MRI e-cycle solutions (Aust) Pty Ltd,17624,35C36432-E238-6845-BB3D83283D9AE171,We offer Australia wide recycling services for...,True,mri@mri.com.au,True,-35.3302340,149.1823900,1300 439 273,2609,Drop Zone ...,ACT,Fyshwick,http://www.mri.com.au
65,"Only AA, AAA, C, D and 9V batteries are accepted.",36 Benham Street,ALDI,18111,D7801E8B-1016-EB32-4A75BD9BE1668AE0,None,True,None,False,-35.4147850,149.1293500,None,2905,None,ACT,Chisholm,None
66,"Only AA, AAA, C, D and 9V batteries are accepted.",36 Benham Street,ALDI,18111,D7801E8B-1016-EB32-4A75BD9BE1668AE0,None,True,None,False,-35.4147850,149.1293500,None,2905,None,ACT,Chisholm,None